### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Sakuravk** [yujincheng08/BiliRoaming#1124]
### 问题描述

开启其他地区番剧搜索后报错，搜索内容后软件重启。

### 复现步骤

打开其他地区番剧搜索

### 预期行为

出现搜索的目标内容

### 实际行为

应用重启

### 安卓版本

13

### 哔哩漫游版本

1.6.11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.31.0

### 使用的框架和版本

LSPosed1.8.6(6712) Zygisk

### 其他

所有番剧都会

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11556668/log.txt)

**Comment by Sakuravk** [comment]
![Screenshot_2023-05-24-20-39-59-794_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/130233388/aba10726-4899-482f-9bae-c7d25631b87a)

**Comment by yujincheng08** [comment]
java.lang.NoClassDefFoundError: com.bilibili.search.result.pages.BiliMainSearchResultPage$PageTypes
	at com.bilibili.search.result.BiliMainSearchResultFragment.ct(BL:4)
	at com.bilibili.search.result.BiliMainSearchResultFragment.dt(BL:1)
	at com.bilibili.search.result.BiliMainSearchResultFragment$d.b(BL:3)
	at com.bilibili.search.result.BiliMainSearchResultDataLoader$searchAllForPageInitNew$1.invokeSuspend(BL:24)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BL:4)
	at kotlinx.coroutines.q0.run(BL:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [d2{Cancelling}@8a0646c, Dispatchers.Main.immediate]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at biliroaming.u0.b(SourceFile:37)
	at me.iacn.biliroaming.XposedInit.a(SourceFile:9)
	at biliroaming.Sg.beforeHookedMethod(SourceFile:543)
	at KJJZaWsiocDGTCy.Sqcs.n.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:456)
	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7078)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 6 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.bilibili.lib.blconfig.Contract com.bilibili.lib.blconfig.ConfigManager.getAb()' on a null object reference
	at com.bilibili.lib.blconfig.ConfigManager$Companion.ab(BL:1)
	at com.bilibili.search.result.pages.BiliMainSearchResultPage$PageTypes.<clinit>(BL:7)
	... 17 more

**Comment by Sakuravk** [comment]
![Uploading Screenshot_2023-05-24-20-39-59-794_tv.danmaku.bili.jpg…]()

**Comment by Sakuravk** [comment]
[
![Screenshot_2023-05-24-20-39-59-794_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/130233388/8945ba8c-e85e-49b1-a203-9c52332218db)
](url)

**Comment by Sakuravk** [comment]
我不小心关了问题

**Comment by Sakuravk** [comment]
不小心关闭了问题

**Comment by yujincheng08** [comment]
标题不写？

**Comment by yujincheng08** [comment]
#1116
