### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Viel0320** [yujincheng08/BiliRoaming#1259]
### 问题描述

lsposed 升级至1.90以上后，在哔哩哔哩7.28.0小版本上模块应用失败并报错，详细请见log
经测试，lsposed在1.86及以下版本时模块应用正常，在7.14及7.45测试表现也正常

### 复现步骤

打开哔哩哔哩7.28即可

### 预期行为

模块正常应用

### 实际行为

模块未正常应用并报错，哔哩哔哩未闪退

### 安卓版本

13

### 哔哩漫游版本

1.6.2及之后ci均可复现

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.28.0

### 使用的框架和版本

1.9.0及以上版本

### 其他

magisk 26301

### 日志

lsposed log:

	BiliRoaming : qHsxllGQ.E.yl.g.XwR.wb.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.bilibili.bangumi.ui.page.detail.BangumiDetailActivityV3
	at qHsxllGQ.E.yl.g.XwR.wb.XposedHelpers.findClass(Unknown Source:12)
	at biliroaming.G0.b(SourceFile:280)
	at me.iacn.biliroaming.XposedInit.a(SourceFile:9)
	at biliroaming.Rj.beforeHookedMethod(SourceFile:543)
	at qHsxllGQ.E.yl.g.XwR.wb.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:179)
	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7083)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Caused by: java.lang.ClassNotFoundException: com.bilibili.bangumi.ui.page.detail.BangumiDetailActivityV3
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at q.a(Unknown Source:16)
	at qHsxllGQ.E.yl.g.XwR.wb.XposedHelpers.findClass(Unknown Source:4)
	... 16 more
	Caused by: java.lang.ClassNotFoundException: com.bilibili.bangumi.ui.page.detail.BangumiDetailActivityV3
	... 20 more

logcat见附件

[logcat.log](https://github.com/yujincheng08/BiliRoaming/files/12517563/logcat.log)

**Comment by yujincheng08** [comment]
7.28 太老了，没用适配计划。

**Comment by cxw620** [comment]
刚刚看了看 `com.bilibili.bangumi.ui.page.detail.BangumiDetailActivityV3` 在 7.28.0 是存在的, 报 ClassNotFoundError 确实有点奇怪

**Comment by Viel0320** [comment]
> 刚刚看了看 `com.bilibili.bangumi.ui.page.detail.BangumiDetailActivityV3` 在 7.28.0 是存在的, 报 ClassNotFoundError 确实有点奇怪

主要是旧版本框架没这问题😞

**Comment by cxw620** [comment]
> 主要是旧版本框架没这问题😞

你试试重新安装一下 7.28.0 版本的哔哩哔哩, 然后在管理器重新启用模块后重启手机看看?

**Comment by Viel0320** [comment]
> > 主要是旧版本框架没这问题😞
> 
> 你试试重新安装一下 7.28.0 版本的哔哩哔哩, 然后在管理器重新启用模块后重启手机看看? 

抱歉现在才回复，我之前是做过这些操作的，但是没用
另外重启手机是什么原因，重新启动模块不需要重启吧，又没有系统框架
