### ISSUE TITLE
[Bug] java.lang.ClassNotFoundException: com.bilibili.search.api.SearchRank

### ISSUE THREAD

**Issue by AlexZhu2001** [yujincheng08/BiliRoaming#1373]
### 问题描述

Bilibili客户端启动时提示java.lang.ClassNotFoundException: com.bilibili.search.api.SearchRank

### 复现步骤

打开B站

### 预期行为

暂不清楚影响范围，可能对搜索的部分功能有影响

### 实际行为

暂不清楚影响范围，可能对搜索的部分功能有影响

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.64.0

### 使用的框架和版本

LSPosed 1.9.2

### 日志

```
01-18 12:41:59.229 32289 32289 D BiliRoaming: startHook: Pegasus
01-18 12:41:59.230 32289 32289 W System  : ClassLoader referenced unknown path: 
01-18 12:41:59.231 32289 32289 D BiliRoaming: startHook: Json
01-18 12:41:59.242 32289 32289 W System  : ClassLoader referenced unknown path: 
01-18 12:41:59.244 32289 32289 E BiliRoaming: h.x.bmY.FvcX.VV.KgVFpe.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.bilibili.search.api.SearchRank
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at h.x.bmY.FvcX.VV.KgVFpe.XposedHelpers.findClass(Unknown Source:12)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at biliroaming.b9.b(SourceFile:344)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at me.iacn.biliroaming.XposedInit.a(SourceFile:9)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at biliroaming.sj.beforeHookedMethod(SourceFile:625)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at h.x.bmY.FvcX.VV.KgVFpe.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at J.callback(Unknown Source:179)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7083)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.os.Looper.loopOnce(Looper.java:210)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.os.Looper.loop(Looper.java:299)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at android.app.ActivityThread.main(ActivityThread.java:8252)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
01-18 12:41:59.244 32289 32289 E BiliRoaming: Caused by: java.lang.ClassNotFoundException: com.bilibili.search.api.SearchRank
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at java.lang.Class.classForName(Native Method)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at java.lang.Class.forName(Class.java:454)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at q.a(Unknown Source:16)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at h.x.bmY.FvcX.VV.KgVFpe.XposedHelpers.findClass(Unknown Source:4)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	... 16 more
01-18 12:41:59.244 32289 32289 E BiliRoaming: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bilibili.search.api.SearchRank" on path: DexPathList[[zip file "/data/app/~~4Az1zfnAsUIyT7OSn9jfmQ==/tv.danmaku.bili-YSFV7Mk12-70wY_CpUWrqw==/base.apk"],nativeLibraryDirectories=[/data/app/~~4Az1zfnAsUIyT7OSn9jfmQ==/tv.danmaku.bili-YSFV7Mk12-70wY_CpUWrqw==/lib/arm64, /data/app/~~4Az1zfnAsUIyT7OSn9jfmQ==/tv.danmaku.bili-YSFV7Mk12-70wY_CpUWrqw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.m(BL:4)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService$PathRootClassLoader.loadClass(BL:1)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	... 20 more
01-18 12:41:59.244 32289 32289 E BiliRoaming: 	Suppressed: java.lang.ClassNotFoundException: Class com.bilibili.search.api.SearchRank not found from all bundle loaders.
01-18 12:41:59.244 32289 32289 E BiliRoaming: 		at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.h(BL:6)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 		at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.i(BL:1)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 		at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.m(BL:3)
01-18 12:41:59.244 32289 32289 E BiliRoaming: 		... 21 more
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: BiliRoaming : h.x.bmY.FvcX.VV.KgVFpe.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.bilibili.search.api.SearchRank
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at h.x.bmY.FvcX.VV.KgVFpe.XposedHelpers.findClass(Unknown Source:12)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at biliroaming.b9.b(SourceFile:344)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at me.iacn.biliroaming.XposedInit.a(SourceFile:9)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at biliroaming.sj.beforeHookedMethod(SourceFile:625)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at h.x.bmY.FvcX.VV.KgVFpe.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at J.callback(Unknown Source:179)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7083)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:210)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:299)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:8252)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: Caused by: java.lang.ClassNotFoundException: com.bilibili.search.api.SearchRank
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at java.lang.Class.classForName(Native Method)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at java.lang.Class.forName(Class.java:454)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at q.a(Unknown Source:16)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at h.x.bmY.FvcX.VV.KgVFpe.XposedHelpers.findClass(Unknown Source:4)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	... 16 more
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bilibili.search.api.SearchRank" on path: DexPathList[[zip file "/data/app/~~4Az1zfnAsUIyT7OSn9jfmQ==/tv.danmaku.bili-YSFV7Mk12-70wY_CpUWrqw==/base.apk"],nativeLibraryDirectories=[/data/app/~~4Az1zfnAsUIyT7OSn9jfmQ==/tv.danmaku.bili-YSFV7Mk12-70wY_CpUWrqw==/lib/arm64, /data/app/~~4Az1zfnAsUIyT7OSn9jfmQ==/tv.danmaku.bili-YSFV7Mk12-70wY_CpUWrqw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.m(BL:4)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService$PathRootClassLoader.loadClass(BL:1)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	... 20 more
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 	Suppressed: java.lang.ClassNotFoundException: Class com.bilibili.search.api.SearchRank not found from all bundle loaders.
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 		at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.h(BL:6)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 		at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.i(BL:1)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 		at com.bilibili.lib.tribe.core.internal.loader.DefaultClassLoaderService.m(BL:3)
01-18 12:41:59.244 32289 32289 I LSPosed-Bridge: 		... 21 more
01-18 12:41:59.244 32289 32289 D BiliRoaming: startHook: Setting
```
[完整日志](https://github.com/yujincheng08/BiliRoaming/files/13972256/log.txt)

**Comment by yujincheng08** [comment]
修过了。
