### ISSUE TITLE
[Bug] 8.4.0版本无法缓存视频

### ISSUE THREAD

**Issue by Eric-Joker** [yujincheng08/BiliRoaming#1499]
### 问题描述

尽管不开启任何功能，只要b站被hook了就无法缓存任何视频，显示“视频解析出错”。

### 复现步骤

1.在xp框架内为哔哩哔哩勾选哔哩漫游
2.确认模块被应用后即便不开启任何功能，随便选个视频尝试缓存

### 预期行为

正常缓存视频

### 实际行为

本应显示下载速度的地方显示“视频解析出错”

### 安卓版本

14

### 哔哩漫游版本

ddf4f1 CI

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.4.0

### 使用的框架和版本

Lsposed 1.8.2

### 其他

8.3.0正常

### 日志

07-13 09:44:38.147 20094 22737 D OpenGLRenderer: endAllActiveAnimators on 0xb400007c0e8de000 (RippleDrawable) with handle 0xb400007c5d0f8d40
07-13 09:44:38.156 20094 22741 D ContentCatcher_injector: Interceptor : notifyActivityStop: tv.danmaku.bili@tv.danmaku.bili.ui.videodownload.VideoDownloadListActivity@17267302
07-13 09:44:38.156 20094 22741 D ContentCatcher_catcher: CatcherHolder : mCatcherList size: 3
07-13 09:44:38.195 15631 17676 W PendingIntent: android.app.StackTrace: New mutable implicit PendingIntent: pkg=tv.danmaku.bili, action=null, featureId=null. This will be blocked once the app targets U+ for security reasons.
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.app.PendingIntent.checkPendingIntent(Unknown Source:155)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.app.PendingIntent.getActivityAsUser(Unknown Source:19)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.app.PendingIntent.getActivity(Unknown Source:23)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.app.PendingIntent.getActivity(Unknown Source:1)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at tv.danmaku.bili.services.videodownload.utils.o.d(BL:47)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at tv.danmaku.bili.services.videodownload.utils.o.o(BL:7)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at k53.f.c(BL:1)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at mi2.f.q(BL:11)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at com.bilibili.videodownloader.service.VideoDownloadService.a(BL:58)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at ei2.i.F(BL:66)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at ei2.i.W(BL:20)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at ei2.i.R(BL:53)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at com.bilibili.videodownloader.service.VideoDownloadService.V(BL:39)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at com.bilibili.videodownloader.service.VideoDownloadService.z(BL:1)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at com.bilibili.videodownloader.service.VideoDownloadService$d.a(BL:102)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at com.bilibili.videodownloader.service.VideoDownloadService$d.handleMessage(BL:71)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.os.Looper.loopOnce(Unknown Source:198)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.os.Looper.loop(Unknown Source:83)
07-13 09:44:38.195 15631 17676 W PendingIntent: 	at android.os.HandlerThread.run(Unknown Source:28)
07-13 09:44:38.205 15631 17675 E IPCThreadState: Binder transaction failure: 8426088/29189/-22
07-13 09:44:38.205 15631 17675 E DownloadNotifier: download notifier remove for exception
07-13 09:44:38.429 15631 16311 I cr_CronetUrlRequestContext: destroyNativeStreamLocked org.chromium.net.impl.CronetBidirectionalStream@4466637
07-13 09:44:38.431 15631 15863 D DDReport: no need
07-13 09:44:38.433 15631 15863 D DDReport: no need
07-13 09:44:38.433 15631 17676 E VideoDownloadManager: manager report download failed: { del }, code: 2001

**Comment by Eric-Joker** [comment]
d7e2a55 CI版本 搭配8.16.0~8.18.0（更低版本我没测试）在开启允许下载版权番剧的情况下无法缓存任何视频
