### ISSUE TITLE
[Bug] 小米hyperOS2.0闪退

### ISSUE THREAD

**Issue by yxok200** [yujincheng08/BiliRoaming#1565]
### 问题描述

小米hyperOS2.0闪退

### 复现步骤

小米hyperOS2.0闪退

### 预期行为

正常打开

### 实际行为

闪退

### 安卓版本

15

### 哔哩漫游版本

1.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.21.0

### 使用的框架和版本

LSP192

### 日志

闪退导不了日志，这是小米关于闪退的日志
![Screenshot_2024-11-17-03-55-07-231_com miui thirdappassistant](https://github.com/user-attachments/assets/99a597d0-756b-4289-a19e-ff8b6800c421)

java.lang.RuntimeException: Unable to instantiate application tv.danmaku.bili.HiltApplication package tv.danmaku.bili: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.bili.HiltApplication" on path: DexPathList[[zip file "/data/app/~~ei0yoYH16GzZvIDT-_3jmw==/tv.danmaku.bili-slee4KBCsOMFR2ecnPDe-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~ei0yoYH16GzZvIDT-_3jmw==/tv.danmaku.bili-slee4KBCsOMFR2ecnPDe-w==/lib/arm64, /data/app/~~ei0yoYH16GzZvIDT-_3jmw==/tv.danmaku.bili-slee4KBCsOMFR2ecnPDe-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1541)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8222)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2652)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.bili.HiltApplication" on path: DexPathList[[zip file "/data/app/~~ei0yoYH16GzZvIDT-_3jmw==/tv.danmaku.bili-slee4KBCsOMFR2ecnPDe-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~ei0yoYH16GzZvIDT-_3jmw==/tv.danmaku.bili-slee4KBCsOMFR2ecnPDe-w==/lib/arm64, /data/app/~~ei0yoYH16GzZvIDT-_3jmw==/tv.danmaku.bili-slee4KBCsOMFR2ecnPDe-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1356)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1534)
	... 11 more

**Comment by CodePwn2021** [comment]
使用的是LSPatch？用支持安卓15的版本打包一遍就能用了，这不是模块的问题。

**Comment by Nyotacahe** [comment]
> 使用的是LSPatch？用支持安卓15的版本打包一遍就能用了，这不是模块的问题。

大佬有没有教程啊，没学过不会打包

**Comment by CodePwn2021** [comment]
> > 使用的是LSPatch？用支持安卓15的版本打包一遍就能用了，这不是模块的问题。
> 
> 大佬有没有教程啊，没学过不会打包

自行解决。
