### ISSUE TITLE
全屏出现卧槽[BUG]

### ISSUE THREAD

**Issue by lolisix** [yujincheng08/BiliRoaming#175]
**问题描述**
打开xpatch版，全部文字被卧槽替代，但是我没有开卧了个槽模块
**复现步骤**
如何复现
1. 打开xpatch版bilibili

**截图**
![Screenshot_2021-06-22-16-41-19-138_org lsposed manager](https://user-images.githubusercontent.com/80681557/122893474-f1ba8080-d378-11eb-86f8-a04ce74c2658.jpg)
![Screenshot_2021-06-22-16-41-31-706_tv danmaku bili](https://user-images.githubusercontent.com/80681557/122893489-f717cb00-d378-11eb-995a-afe58eaddd2b.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI12.0.10
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：xpatch版1.4.4
 - 使用的框架和版本：Lsposed 1.4.5(5767)

**日志**

> LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Redmi
Device: apollo
Product: apollo
Model: M2007J3SC
Fingerprint: Redmi/apollo/apollo:10/QKQ1.200419.002/V12.0.10.0.QJDCNXM:user/release-keys
ROM description: apollo-user 10 QKQ1.200419.002 V12.0.10.0.QJDCNXM release-keys
Architecture: arm64-v8a
Android build: QKQ1.200419.002
Android version: 10
Android sdk: 29
LSPosed version: v1.4.5 (5767)
Riru version: v25.4.4.r426.05efc94 (426)
Riru api: 25
Magisk: 23.0 (23000)
2021-06-22 08:33:10.010 E/android(1289-1289): java.lang.NoSuchMethodError: com.android.server.am.ActivityManagerService#checkBroadcastFromSystem(android.content.Intent,com.android.server.am.ProcessRecord,java.lang.String,int,boolean,java.util.List)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:4)
	at a.a.a.f.c.handleLoadPackage(:1)
	at a.a.a.b.a(:2)
	at com.chenyue404.intentfilter.PluginEntry.handleLoadPackage(Unknown Source:7)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at I0.beforeHookedMethod(:1)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:8)
	at com.android.server.SystemServer.run(SystemServer.java:526)
	at com.android.server.SystemServer.main(SystemServer.java:365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:931)

2021-06-22 08:33:29.029 I/com.android.thememanager(7182-7182): --ChiMi--Hook ThemeManagerVersionCode:955 Success
2021-06-22 08:33:40.040 I/com.tencent.mm(9105-9105): [ExLink] 进行了初始化规则
2021-06-22 08:33:40.040 I/com.tencent.mm(9105-9105): [ExLink Error] Permission denied
2021-06-22 08:33:40.040 I/com.tencent.mm(9105-9105): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:33:40.040 I/com.tencent.mm(9105-9105): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:33:40.040 I/com.tencent.mm(9105-9105): com.tencent.mm loading com.fkzhang.wechatxposed
2021-06-22 08:33:42.042 I/com.tencent.mm(9105-9105): com.fkzhang.wechatxposed [WechatXposed](2.21|83): wechat version 8.0.0(1820)
2021-06-22 08:33:42.042 I/com.tencent.mm(9105-9105): com.fkzhang.wechatxposed load time: 1736
2021-06-22 08:33:42.042 I/com.tencent.mm(9105-9194): 微X模块 2.21_3.18 (7,99) p
2021-06-22 08:33:42.042 I/com.tencent.mm(9105-9189): feature loaded: base 186
2021-06-22 08:33:43.043 I/com.tencent.mm(9105-9194): Wechat: 8.0.0_1820 {64bit} (0x28000031)[607f76b0]
2021-06-22 08:33:43.043 I/com.tencent.mm:push(9386-9386): [ExLink] 进行了初始化规则
2021-06-22 08:33:43.043 I/com.tencent.mm:push(9386-9386): [ExLink Error] Permission denied
2021-06-22 08:33:43.043 I/com.tencent.mm:push(9386-9386): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:33:43.043 I/com.tencent.mm:push(9386-9386): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand1(9604-9604): [ExLink] 进行了初始化规则
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand1(9604-9604): [ExLink Error] Permission denied
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand1(9604-9604): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand1(9604-9604): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand0(9630-9630): [ExLink] 进行了初始化规则
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand0(9630-9630): [ExLink Error] Permission denied
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand0(9630-9630): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:33:45.045 I/com.tencent.mm:appbrand0(9630-9630): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:33:55.055 I/com.tencent.mm:appbrand1(11211-11211): [ExLink] 进行了初始化规则
2021-06-22 08:33:55.055 I/com.tencent.mm:appbrand1(11211-11211): [ExLink Error] Permission denied
2021-06-22 08:33:55.055 I/com.tencent.mm:appbrand1(11211-11211): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:33:55.055 I/com.tencent.mm:appbrand1(11211-11211): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:34:05.005 I/com.tencent.mm:appbrand0(12873-12873): [ExLink] 进行了初始化规则
2021-06-22 08:34:05.005 I/com.tencent.mm:appbrand0(12873-12873): [ExLink Error] Permission denied
2021-06-22 08:34:05.005 I/com.tencent.mm:appbrand0(12873-12873): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:34:05.005 I/com.tencent.mm:appbrand0(12873-12873): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:34:12.012 I/com.tencent.mm:appbrand1(13768-13768): [ExLink] 进行了初始化规则
2021-06-22 08:34:12.012 I/com.tencent.mm:appbrand1(13768-13768): [ExLink Error] Permission denied
2021-06-22 08:34:12.012 I/com.tencent.mm:appbrand1(13768-13768): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:34:12.012 I/com.tencent.mm:appbrand1(13768-13768): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:34:14.014 I/com.tencent.mm:toolsmp(14027-14027): [ExLink] 进行了初始化规则
2021-06-22 08:34:14.014 I/com.tencent.mm:toolsmp(14027-14027): [ExLink Error] Permission denied
2021-06-22 08:34:14.014 I/com.tencent.mm:toolsmp(14027-14027): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:34:14.014 I/com.tencent.mm:toolsmp(14027-14027): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:34:43.043 I/com.tencent.mm(9105-9341): Software caused connection abort
2021-06-22 08:34:54.054 I/com.tencent.mm(9105-9105): wexposed strings file update success!
2021-06-22 08:34:56.056 I/com.tencent.mm:appbrand0(15845-15845): [ExLink] 进行了初始化规则
2021-06-22 08:34:56.056 I/com.tencent.mm:appbrand0(15845-15845): [ExLink Error] Permission denied
2021-06-22 08:34:56.056 I/com.tencent.mm:appbrand0(15845-15845): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:34:56.056 I/com.tencent.mm:appbrand0(15845-15845): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:35:30.030 I/com.tencent.mm(9105-9355): timeout
2021-06-22 08:35:45.045 I/com.tencent.mm:appbrand1(17611-17611): [ExLink] 进行了初始化规则
2021-06-22 08:35:45.045 I/com.tencent.mm:appbrand1(17611-17611): [ExLink Error] Permission denied
2021-06-22 08:35:45.045 I/com.tencent.mm:appbrand1(17611-17611): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:35:45.045 I/com.tencent.mm:appbrand1(17611-17611): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:35:54.054 I/com.miui.packageinstaller(17916-17916): ErrorHook: com.android.packageinstaller.xa#d
2021-06-22 08:36:13.013 I/com.tencent.mm:appbrand0(18818-18818): [ExLink] 进行了初始化规则
2021-06-22 08:36:13.013 I/com.tencent.mm:appbrand0(18818-18818): [ExLink Error] Permission denied
2021-06-22 08:36:13.013 I/com.tencent.mm:appbrand0(18818-18818): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:36:13.013 I/com.tencent.mm:appbrand0(18818-18818): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:39:54.054 I/com.coolapk.market(25706-25706): FUCKCOOLAPK : java.lang.NoSuchMethodError: com.coolapk.market.CoolMarketApplication#checkCoolapkUpgradeInfo()#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at 胡松华你这个逆子.胡松华你个逆子早晚懒趴掉下来.胡松华你个逆子早晚懒趴掉下来.胡松华去你妈的烂逼.胡松华丢你老母个嗨.a(Unknown Source:10)
	at com.bytedance.sdk.openadsdk.a.d.胡松华丢你老母个嗨(:133)
	at com.bytedance.sdk.openadsdk.a.d$胡松华丢你老母个嗨.afterHookedMethod(:5)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:376)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1222)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

2021-06-22 08:41:10.010 I/com.tencent.mm:appbrand1(27967-27967): [ExLink] 进行了初始化规则
2021-06-22 08:41:10.010 I/com.tencent.mm:appbrand1(27967-27967): [ExLink Error] Permission denied
2021-06-22 08:41:10.010 I/com.tencent.mm:appbrand1(27967-27967): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:41:10.010 I/com.tencent.mm:appbrand1(27967-27967): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:43:07.007 I/com.tencent.mm:appbrand0(31738-31738): [ExLink] 进行了初始化规则
2021-06-22 08:43:07.007 I/com.tencent.mm:appbrand0(31738-31738): [ExLink Error] Permission denied
2021-06-22 08:43:07.007 I/com.tencent.mm:appbrand0(31738-31738): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:43:07.007 I/com.tencent.mm:appbrand0(31738-31738): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:46:07.007 I/com.tencent.mm:appbrand1(6742-6742): [ExLink] 进行了初始化规则
2021-06-22 08:46:07.007 I/com.tencent.mm:appbrand1(6742-6742): [ExLink Error] Permission denied
2021-06-22 08:46:07.007 I/com.tencent.mm:appbrand1(6742-6742): [ExLink Error] 创建 json 文件异常/data/user_de/0/com.xloger.exlink.app/exlink.json
2021-06-22 08:46:07.007 I/com.tencent.mm:appbrand1(6742-6742): [ExLink] 进入微信(com.tencent.mm)
2021-06-22 08:47:39.039 I/com.coolapk.market(9789-9789): FUCKCOOLAPK : java.lang.NoSuchMethodError: com.coolapk.market.CoolMarketApplication#checkCoolapkUpgradeInfo()#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at 胡松华你这个逆子.胡松华你个逆子早晚懒趴掉下来.胡松华你个逆子早晚懒趴掉下来.胡松华去你妈的烂逼.胡松华丢你老母个嗨.a(Unknown Source:10)
	at com.bytedance.sdk.openadsdk.a.d.胡松华丢你老母个嗨(:133)
	at com.bytedance.sdk.openadsdk.a.d$胡松华丢你老母个嗨.afterHookedMethod(:5)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:376)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1222)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

2021-06-22 08:47:50.050 I/com.coolapk.market(9789-9789): FUCKCOOLAPK : java.lang.ExceptionInInitializerError
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.胡松华憨憨.胡松华你这个逆子(:52)
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.林北一拳打爆你妈的脑袋.胡松华丢你老母个嗨(:2)
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你老母个烂ham.胡松华你个逆子早晚懒趴掉下来.胡松华丢你老母个嗨(:7)
	at 胡松华你妈有逼吗.胡松华丢你老母个嗨.胡松华丢你老母个嗨.胡松华去你妈的烂逼$胡松华丢你老母个臭嗨.beforeHookedMethod(Unknown Source:14)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.convert(Unknown Source:18)
	at com.coolapk.market.binding.TextViewBindingAdapters.setTextViewLinkable(TextViewBindingAdapters.java:99)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.setTextViewLinkable(Unknown Source:26)
	at com.coolapk.market.extend.ViewExtendsKt.setBriefMessage(ViewExtends.kt:292)
	at com.coolapk.market.view.cardlist.EntityDataHelper$FeedAssistData.<init>(EntityDataHelper.kt:70)
	at com.coolapk.market.view.cardlist.EntityDataHelper.generateAssistDataFor(EntityDataHelper.kt:53)
	at com.coolapk.market.view.cardlist.EntityDataHelper.access$generateAssistDataFor(EntityDataHelper.kt:18)
	at com.coolapk.market.view.cardlist.EntityDataHelper$postUpdataAssistData$1.run(EntityDataHelper.kt:38)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.逆向.胡松华丢你老母个臭嗨.<clinit>(:1)
	... 22 more

2021-06-22 08:50:24.024 I/com.coolapk.market(9789-9789): FUCKCOOLAPK : java.lang.NoClassDefFoundError: 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.逆向.胡松华丢你老母个臭嗨
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.胡松华憨憨.胡松华你这个逆子(:52)
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.林北一拳打爆你妈的脑袋.胡松华丢你老母个嗨(:2)
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你老母个烂ham.胡松华你个逆子早晚懒趴掉下来.胡松华丢你老母个嗨(:7)
	at 胡松华你妈有逼吗.胡松华丢你老母个嗨.胡松华丢你老母个嗨.胡松华去你妈的烂逼$胡松华丢你老母个臭嗨.beforeHookedMethod(Unknown Source:14)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.convert(Unknown Source:18)
	at com.coolapk.market.binding.TextViewBindingAdapters.setTextViewLinkable(TextViewBindingAdapters.java:99)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.setTextViewLinkable(Unknown Source:26)
	at com.coolapk.market.extend.ViewExtendsKt.setBriefMessage(ViewExtends.kt:292)
	at com.coolapk.market.view.cardlist.EntityDataHelper$FeedAssistData.<init>(EntityDataHelper.kt:70)
	at com.coolapk.market.view.cardlist.EntityDataHelper.generateAssistDataFor(EntityDataHelper.kt:53)
	at com.coolapk.market.view.cardlist.EntityDataHelper.access$generateAssistDataFor(EntityDataHelper.kt:18)
	at com.coolapk.market.view.cardlist.EntityDataHelper$postUpdataAssistData$1.run(EntityDataHelper.kt:38)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.ExceptionInInitializerError
	... 22 more
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at 胡松华去你妈的烂逼.胡松华丢你老母个臭嗨.胡松华你个逆子早晚懒趴掉下来.逆向.胡松华丢你老母个臭嗨.<clinit>(:1)
	... 22 more

**Comment by yujincheng08** [comment]
怪人。明明有 LSPosed 为什么用 xpatch。而且 xpatch 版本来就是自动加载所有模块的，这是 feature。最后，xpatch 版本和 lspatch 都有配置生效模块的方法，自行搜索吧。
