### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sym1018** [yujincheng08/BiliRoaming#383]
**问题描述**
客户端开启时多数情况下会闪退
有时会弹出报错弹窗，如下截图
偶尔可以正常开启使用（等待时间较长）
清除缓存后可以修复，但登陆账号后会复现

**复现步骤**
如何复现
1. 打开客户端
2. 点击
3. 出现闪退状况

**截图**
![Screenshot_20220111_223637_tv danmaku bili](https://user-images.githubusercontent.com/46147899/148967842-bec88d81-76f8-4674-ab96-e58468a8961d.jpg)

**环境信息**
 - 安卓版本：harmony 2.0.0
 - 系统版本：huawei p20
 - 哔哩漫游版本：1.5.5
 - 哔哩哔哩版本和版本号：哔哩哔哩 6.55.0 (6550400) tv.danmaku.bili
 - 使用的框架和版本：LSPatch 1.5.5 6.55.0
 - 其他：

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7847565/log.txt)

**Comment by yujincheng08** [comment]
```
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   native: #01 pc 0000000000432c04  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 366000) (art::DexFile_getClassNameList(_JNIEnv*, _jclass*, _jobject*)+360)
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   at dalvik.system.DexFile.getClassNameList(Native method)
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   at dalvik.system.DexFile.access$100(DexFile.java:43)
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   at dalvik.system.DexFile$DFEnum.<init>(DexFile.java:325)
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   at dalvik.system.DexFile.entries(DexFile.java:312)
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   at java.lang.reflect.Method.invoke(Native method)
01-11 22:36:21.159 19597 19625 F tv.danmaku.bil: runtime.cc:668]   at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1363)
```
鸿蒙问题，无解。

**Comment by sym1018** [comment]
> 

好的
