### ISSUE TITLE
[Bug] Android 7.1.2 libbiliroaming.so动态库加载失败问题

### ISSUE THREAD

**Issue by cecilia-little1** [yujincheng08/BiliRoaming#829]
### 问题描述

Android版本：7.1.2 arm64
Xposed Framework版本：89

在此环境中使用biliroaming 1.6.6版时，启动bilibili app（版本7.1.2）时报告了以下Toast：
> 不支持该架构或框架，部分功能可能失效

P.S.：此处的bilibili版本与Android版本**的确均为**7.1.2

随后定位到报告此消息的[源代码](https://github.com/yujincheng08/BiliRoaming/blob/master/app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt#L353)：
```
try {
    System.loadLibrary("biliroaming")
} catch (e: Throwable) {
    Log.e(e)
    Log.toast("不支持该架构或框架，部分功能可能失效")
    return@hookInfo
}
```
可以确定，`System.loadLibrary("biliroaming")`抛出了异常，随即提取其异常堆栈信息：
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.iacn.biliroaming-1/base.apk"],nativeLibraryDirectories=[system/lib64,/vendor/lib64]]] couldn't find "libbiliroaming.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
	at java.lang.System.loadLibrary(System.java:1562)
	at biliroaming.o2.j(SourceFile)
	at biliroaming.T2.<init>(SourceFile:3)
	at biliroaming.ue.beforeHookedMethod(SourceFile:3)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
	...
```
通过异常信息可以发现，`loadLibrary()`方法并没有尝试从apk包中读取相应架构的动态链接库。

### 复现步骤

在上述环境下打开bilibili app即可复现

### 预期行为

模块正常加载

### 实际行为

启动时Toast提示：
> 不支持该架构或框架，部分功能可能失效

### 安卓版本

7.1.2

### 哔哩漫游版本

1.6.6

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.1.2

### 使用的框架和版本

Xposed Framework 89（Xposed Installer）

### 日志

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.iacn.biliroaming-1/base.apk"],nativeLibraryDirectories=[system/lib64,/vendor/lib64]]] couldn't find "libbiliroaming.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
	at java.lang.System.loadLibrary(System.java:1562)
	at biliroaming.o2.j(SourceFile)
	at biliroaming.T2.<init>(SourceFile:3)
	at biliroaming.ue.beforeHookedMethod(SourceFile:3)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
	...
```

**Comment by yujincheng08** [comment]
用 LSPosed 或太极。不支持其他框架。
